version: "2"
services:
  mysql:
    image: mysql:5.7.23
    ports:
    - 3306:3306
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: server
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ci
