version: "2"
services:
  reservation_mysql:
    image: mysql:5.7.23
    ports:
    - 3306:3306
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: reservation
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ci
  reservation_web:
    container_name: reservation_web
    build: .
    volumes:
      - ../../:/opt/home/
#      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /opt/home/Reservation-Sysu
    environment:
      IS_DOCKER: 1
    ports:
      - 8080:8080
    depends_on:
      - reservation_mysql
    entrypoint: ['bash', '-c', 'gunicorn -w 1 server:app -b 0.0.0.0:8080 --reload']

